/**
 * README Generator
 *
 * Generates vault README.md with overview and navigation.
 */

import { join } from 'path';
import { writeMarkdownFile } from './markdown-writer.js';
import type { GeneratedNode } from '../types.js';

/**
 * Generate vault README.md
 */
export async function generateVaultReadme(nodes: GeneratedNode[], vaultPath: string): Promise<string> {
  const readmePath = join(vaultPath, 'README.md');

  // Count nodes by type
  const conceptNodes = nodes.filter((n) => n.type === 'concept');
  const technicalNodes = nodes.filter((n) => n.type === 'technical');
  const featureNodes = nodes.filter((n) => n.type === 'feature');

  const content = `# Knowledge Vault

This vault was automatically generated using the Weaver vault initialization system.

## Overview

- **Total Nodes**: ${nodes.length}
- **Concepts**: ${conceptNodes.length}
- **Technical Specs**: ${technicalNodes.length}
- **Features**: ${featureNodes.length}

## Structure

\`\`\`
vault/
├── concepts/           # Conceptual knowledge nodes
├── technical/          # Technical specifications
├── features/           # Feature descriptions
├── concept-map.md      # Visual concept map
└── README.md           # This file
\`\`\`

## Quick Navigation

### Concepts
${generateNodeList(conceptNodes, 'concepts')}

### Technical Specs
${generateNodeList(technicalNodes, 'technical')}

### Features
${generateNodeList(featureNodes, 'features')}

## Using This Vault

This vault is designed to be used with Obsidian or any markdown-compatible knowledge management system.

### Recommended Plugins (Obsidian)
- **Dataview**: Query and analyze vault data
- **Graph View**: Visualize connections
- **Tag Pane**: Browse by tags

### Navigation
- Use the **Graph View** to explore relationships
- Check **concept-map.md** for a high-level overview
- Browse by directory for organized access

## Maintenance

The vault is designed to be self-maintaining through the shadow cache system:
- All changes are tracked automatically
- Links are validated and indexed
- Tags are organized and searchable

---

*Generated by Weaver Vault Initialization System*
*${new Date().toISOString()}*
`;

  await writeMarkdownFile(readmePath, content);

  return readmePath;
}

/**
 * Generate a list of nodes with links
 */
function generateNodeList(nodes: GeneratedNode[], directory: string): string {
  if (nodes.length === 0) {
    return '*No nodes in this category*\n';
  }

  // Sort by title
  const sorted = [...nodes].sort((a, b) => a.title.localeCompare(b.title));

  // Take first 20 for README (to avoid very long lists)
  const displayNodes = sorted.slice(0, 20);
  const hasMore = sorted.length > 20;

  let list = displayNodes.map((node) => `- [[${directory}/${node.filename}|${node.title}]]`).join('\n');

  if (hasMore) {
    list += `\n\n*...and ${sorted.length - 20} more. Browse the \`${directory}/\` folder for all nodes.*`;
  }

  return list + '\n';
}

/**
 * Generate a statistics section
 */
export function generateVaultStats(nodes: GeneratedNode[]): string {
  const totalLinks = nodes.reduce((sum, node) => sum + (node.links?.length || 0), 0);
  const totalTags = nodes.reduce((sum, node) => sum + (node.tags?.length || 0), 0);
  const uniqueTags = new Set(nodes.flatMap((node) => node.tags || []));

  return `
## Statistics

- **Total Nodes**: ${nodes.length}
- **Total Links**: ${totalLinks}
- **Total Tags**: ${totalTags}
- **Unique Tags**: ${uniqueTags.size}
- **Average Links per Node**: ${(totalLinks / nodes.length).toFixed(1)}
- **Average Tags per Node**: ${(totalTags / nodes.length).toFixed(1)}
`;
}
