# Python packages installation for Weave-NN

install_python_packages:
  pip.installed:
    - pkgs: {{ pillar['weave_nn']['python_packages'] }}
    - bin_env: {{ pillar['weave_nn']['python']['venv_path'] }}
    - user: {{ pillar['weave_nn']['user']['name'] }}
    - require:
      - cmd: python_venv

# Create requirements.txt for reference
python_requirements_file:
  file.managed:
    - name: {{ pillar['weave_nn']['user']['home'] }}/weave-nn/requirements.txt
    - user: {{ pillar['weave_nn']['user']['name'] }}
    - group: {{ pillar['weave_nn']['user']['name'] }}
    - mode: 644
    - contents: |
        # Weave-NN Python Dependencies
        # Auto-generated by SaltStack

        # Web framework
        fastapi
        uvicorn[standard]

        # Message queue
        pika

        # HTTP client
        requests

        # Configuration
        pyyaml
        python-dotenv

        # File watching
        watchdog

        # Git integration
        gitpython

        # Database
        aiosqlite

        # Development
        pytest
        pytest-asyncio
        black
        ruff
    - require:
      - file: weave_nn_directory
