#!/usr/bin/env bash
# Automated Task Log Generator
# Called by Claude-Flow post-task hook to create task logs automatically

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}/.."
TASK_LOGS_DIR="${PROJECT_ROOT}/_log/tasks"
TEMPLATE_FILE="${PROJECT_ROOT}/templates/task-log-template.md"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get task information from environment variables or parameters
TASK_ID="${TASK_ID:-${1:-}}"
PHASE="${PHASE:-${2:-0}}"
DAY="${DAY:-$(date +%d)}"
TASK_NAME="${TASK_NAME:-${3:-Unknown Task}}"
SUBTASK_NAME="${SUBTASK_NAME:-${4:-}}"
STATUS="${STATUS:-completed}"
AGENT="${AGENT:-$(whoami)}"

# Generate hash for unique filename
HASH=$(echo "$TASK_NAME-$(date +%s)" | md5sum | head -c 6)

# Create filename: [phase].[day].[task].[subtask].[hash].md
if [ -n "$SUBTASK_NAME" ]; then
    FILENAME="${PHASE}.${DAY}.${TASK_NAME// /_}.${SUBTASK_NAME// /_}.${HASH}.md"
else
    FILENAME="${PHASE}.${DAY}.${TASK_NAME// /_}.1.${HASH}.md"
fi

# Ensure logs directory exists
mkdir -p "$TASK_LOGS_DIR"

TASK_LOG_PATH="${TASK_LOGS_DIR}/${FILENAME}"

echo -e "${BLUE}=== Automated Task Log Generator ===${NC}"
echo "Creating task log: $FILENAME"
echo

# Check if template exists
if [ ! -f "$TEMPLATE_FILE" ]; then
    echo -e "${YELLOW}Warning: Template not found at $TEMPLATE_FILE${NC}"
    echo "Creating basic task log without template..."

    # Create minimal task log
    cat > "$TASK_LOG_PATH" << EOF
---
type: task_log
task_id: "${PHASE}.${DAY}.${TASK_NAME// /_}.${SUBTASK_NAME// /_}.${HASH}"
phase: "${PHASE}"
day: "${DAY}"
task_name: "${TASK_NAME}"
subtask_name: "${SUBTASK_NAME}"
agent: "${AGENT}"
priority: "medium"
start_time: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
end_time: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
duration_minutes: 0
status: "${STATUS}"
success: true
quality_score: 0.0

memory_types: []
approach: ""
challenges: []
solutions: []
lessons_learned: []

files_modified: 0
lines_added: 0
lines_removed: 0
tests_added: 0
test_coverage: 0.0

related_concepts: []
related_features: []
related_decisions: []
tags:
  - task-log
  - auto-generated
cssclasses:
  - task-log
---

# Task Log: ${TASK_NAME}

**Task ID**: \`${PHASE}.${DAY}.${TASK_NAME// /_}.${SUBTASK_NAME// /_}.${HASH}\`
**Agent**: ${AGENT}
**Date**: $(date +%Y-%m-%d)
**Status**: ✅ ${STATUS}

---

## 📋 Task Overview

**Objective**:
[Automatically generated task log - please fill in details]

**Context**:
Task completed via automated workflow hook.

**Success Criteria**:
- [ ] Task completed
- [ ] Files modified
- [ ] Tests passing

---

## 💡 Notes

This task log was automatically generated by the Claude-Flow post-task hook.
Please edit this file to add:
- Implementation details
- Challenges encountered
- Solutions applied
- Lessons learned
- Metrics and performance data

---

**Signed**: ${AGENT}
**Date**: $(date '+%Y-%m-%d %H:%M:%S')
**Log File**: \`_log/tasks/${FILENAME}\`
EOF

else
    # Copy template and fill in basic information
    cp "$TEMPLATE_FILE" "$TASK_LOG_PATH"

    # Use sed to replace placeholders in the template
    sed -i "s/task_id: \".*\"/task_id: \"${PHASE}.${DAY}.${TASK_NAME// /_}.${SUBTASK_NAME// /_}.${HASH}\"/" "$TASK_LOG_PATH"
    sed -i "s/phase: \".*\"/phase: \"${PHASE}\"/" "$TASK_LOG_PATH"
    sed -i "s/day: \".*\"/day: \"${DAY}\"/" "$TASK_LOG_PATH"
    sed -i "s/task_name: \".*\"/task_name: \"${TASK_NAME}\"/" "$TASK_LOG_PATH"
    sed -i "s/subtask_name: \".*\"/subtask_name: \"${SUBTASK_NAME}\"/" "$TASK_LOG_PATH"
    sed -i "s/agent: \".*\"/agent: \"${AGENT}\"/" "$TASK_LOG_PATH"
    sed -i "s/status: \".*\"/status: \"${STATUS}\"/" "$TASK_LOG_PATH"
    sed -i "s/start_time: \".*\"/start_time: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"/" "$TASK_LOG_PATH"
    sed -i "s/end_time: \".*\"/end_time: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"/" "$TASK_LOG_PATH"
fi

echo -e "${GREEN}✅ Task log created: ${TASK_LOG_PATH}${NC}"
echo
echo "Task ID: ${PHASE}.${DAY}.${TASK_NAME// /_}.${SUBTASK_NAME// /_}.${HASH}"
echo "Path: _log/tasks/${FILENAME}"
echo
echo -e "${YELLOW}📝 Please edit the task log to add implementation details${NC}"

# Optional: Trigger daily log generation if it's end of day
# Uncomment to enable:
# if [ "$(date +%H)" -ge "23" ]; then
#     echo "Triggering daily log generation..."
#     "$SCRIPT_DIR/daily-log-generator.sh" "$(date +%Y-%m-%d)"
# fi

exit 0
