#!/bin/bash
# Weaver Implementation Merge Script
# Generated by Hive Mind Coder Agent
# Date: 2025-10-28
#
# This script merges the nested Phase 12 implementation into the root weaver

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Base paths
ROOT="/home/aepod/dev/weave-nn/weaver/src"
NESTED="/home/aepod/dev/weave-nn/weave-nn/weaver/src"
BACKUP="/home/aepod/dev/weave-nn/.merge-backup"

echo -e "${GREEN}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     Weaver Implementation Merge - Phase 12 Features   ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to print section headers
print_section() {
    echo -e "\n${YELLOW}▶ $1${NC}"
}

# Function to print success
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

# Function to print warning
print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

# Function to print error
print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# ============================================================================
# PHASE 0: BACKUP
# ============================================================================

print_section "PHASE 0: Creating Backup"

if [ -d "$BACKUP" ]; then
    print_warning "Backup directory exists. Removing old backup..."
    rm -rf "$BACKUP"
fi

mkdir -p "$BACKUP"
cp -r "$ROOT" "$BACKUP/root-backup"
print_success "Root implementation backed up to $BACKUP/root-backup"

# ============================================================================
# PHASE 1: DIRECT COPY (41 files - No conflicts)
# ============================================================================

print_section "PHASE 1: Direct Copy of Phase 12 Features (41 files)"

# 1.1 Learning Loop System (11 files)
print_warning "Copying Learning Loop System..."
mkdir -p "$ROOT/workflows/learning-loop"
cp -r "$NESTED/workflows/learning-loop/"* "$ROOT/workflows/learning-loop/"
print_success "Learning loop system copied (11 files)"

# 1.2 Reasoning System (4 files)
print_warning "Copying Reasoning System..."
mkdir -p "$ROOT/reasoning"
cp -r "$NESTED/reasoning/"* "$ROOT/reasoning/"
print_success "Reasoning system copied (4 files)"

# 1.3 Reflection System (3 files)
print_warning "Copying Reflection System..."
mkdir -p "$ROOT/reflection"
cp -r "$NESTED/reflection/"* "$ROOT/reflection/"
print_success "Reflection system copied (3 files)"

# 1.4 Execution System (2 files)
print_warning "Copying Execution System..."
mkdir -p "$ROOT/execution"
cp "$NESTED/execution/error-recovery.ts" "$ROOT/execution/"
cp "$NESTED/execution/state-verifier.ts" "$ROOT/execution/"
print_success "Execution system copied (2 files)"

# 1.5 Integration Layer (2 files)
print_warning "Copying Integration Layer..."
mkdir -p "$ROOT/integration"
cp "$NESTED/integration/index.ts" "$ROOT/integration/"
cp "$NESTED/integration/unified-memory.ts" "$ROOT/integration/"
print_success "Integration layer copied (2 files)"

# 1.6 Specialized Agents (2 files)
print_warning "Copying Specialized Agents..."
cp "$NESTED/agents/planning-expert.ts" "$ROOT/agents/"
cp "$NESTED/agents/error-detector.ts" "$ROOT/agents/"
print_success "Specialized agents copied (2 files)"

# 1.7 Workflow Extensions (4 files)
print_warning "Copying Workflow Extensions..."
cp "$NESTED/workflows/experience-integration.ts" "$ROOT/workflows/"
cp "$NESTED/workflows/learning-loop-workflows.ts" "$ROOT/workflows/"
cp "$NESTED/workflows/register-workflows.ts" "$ROOT/workflows/"
cp "$NESTED/workflows/vector-db-workflows.ts" "$ROOT/workflows/"
print_success "Workflow extensions copied (4 files)"

# 1.8 Enhanced Utilities (4 files)
print_warning "Copying Enhanced Utilities..."
cp "$NESTED/chunking/utils/boundary-detector.ts" "$ROOT/chunking/utils/"
cp "$NESTED/chunking/utils/context-extractor.ts" "$ROOT/chunking/utils/"
cp "$NESTED/chunking/utils/similarity.ts" "$ROOT/chunking/utils/"
cp "$NESTED/chunking/plugins/index.ts" "$ROOT/chunking/plugins/"
print_success "Enhanced utilities copied (4 files)"

# 1.9 Embedding Extensions (3 files)
print_warning "Copying Embedding Extensions..."
mkdir -p "$ROOT/embeddings/models"
mkdir -p "$ROOT/embeddings/storage"
cp "$NESTED/embeddings/models/model-manager.ts" "$ROOT/embeddings/models/"
cp "$NESTED/embeddings/storage/vector-storage.ts" "$ROOT/embeddings/storage/"
cp "$NESTED/embeddings/batch-processor.ts" "$ROOT/embeddings/"
print_success "Embedding extensions copied (3 files)"

# 1.10 Memory Extensions (2 files)
print_warning "Copying Memory Extensions..."
cp "$NESTED/memory/experience-storage.ts" "$ROOT/memory/"
cp "$NESTED/memory/experience-indexer.ts" "$ROOT/memory/"
print_success "Memory extensions copied (2 files)"

# 1.11 Autonomous Loop (1 file)
print_warning "Copying Autonomous Loop..."
mkdir -p "$ROOT/learning-loop"
cp "$NESTED/learning-loop/autonomous-loop.ts" "$ROOT/learning-loop/"
print_success "Autonomous loop copied (1 file)"

# 1.12 Perception Extension (1 file)
print_warning "Copying Perception Extension..."
cp "$NESTED/perception/data-parser.ts" "$ROOT/perception/"
print_success "Perception extension copied (1 file)"

print_success "PHASE 1 COMPLETE: 41 files copied successfully"

# ============================================================================
# PHASE 2: TYPE SYSTEM MERGES
# ============================================================================

print_section "PHASE 2: Type System Merges"

# 2.1 Memory Types - Rename nested to avoid conflict
print_warning "Handling memory type conflict..."
cp "$NESTED/memory/types.ts" "$ROOT/memory/experience-types.ts"
print_success "Created memory/experience-types.ts (learning types)"
print_warning "Root memory/types.ts preserved (vault sync types)"

# 2.2 Embeddings Types - Manual merge needed
print_warning "Embeddings types require manual merge"
cp "$NESTED/embeddings/types.ts" "$ROOT/embeddings/types-phase12.ts"
print_success "Created embeddings/types-phase12.ts for manual merge"
print_warning "TODO: Manually merge embeddings/types.ts and embeddings/types-phase12.ts"

print_success "PHASE 2 COMPLETE: Type renames done, manual merge required"

# ============================================================================
# PHASE 3: PLUGIN MERGES (Manual - Create comparison files)
# ============================================================================

print_section "PHASE 3: Plugin Merge Preparation"

MERGE_DIR="$ROOT/../merge-comparison"
mkdir -p "$MERGE_DIR/plugins"

# Create comparison files for manual merge
print_warning "Creating comparison files for manual plugin merges..."

for plugin in base-chunker event-based-chunker preference-signal-chunker step-based-chunker; do
    if [ -f "$ROOT/chunking/plugins/${plugin}.ts" ] && [ -f "$NESTED/chunking/plugins/${plugin}.ts" ]; then
        cp "$ROOT/chunking/plugins/${plugin}.ts" "$MERGE_DIR/plugins/${plugin}-root.ts"
        cp "$NESTED/chunking/plugins/${plugin}.ts" "$MERGE_DIR/plugins/${plugin}-nested.ts"
        print_success "Comparison files created for ${plugin}"
    fi
done

print_warning "TODO: Manually merge files in $MERGE_DIR/plugins/"
print_success "PHASE 3 COMPLETE: Comparison files ready for manual merge"

# ============================================================================
# PHASE 4: UPDATE PACKAGE.JSON
# ============================================================================

print_section "PHASE 4: Checking Dependencies"

NESTED_DEPS=$(cat "$NESTED/../package.json" | grep -A 10 '"dependencies"' || true)

if [ -n "$NESTED_DEPS" ]; then
    print_warning "Nested package.json has dependencies:"
    echo "$NESTED_DEPS"
    print_warning "TODO: Check if these need to be added to root package.json"
else
    print_success "No additional dependencies found"
fi

# ============================================================================
# PHASE 5: TYPE CHECK
# ============================================================================

print_section "PHASE 5: Running Type Check"

cd /home/aepod/dev/weave-nn/weaver

if npm run typecheck 2>&1 | tee /tmp/typecheck.log; then
    print_success "Type check passed!"
else
    print_error "Type check failed. See /tmp/typecheck.log for details"
    print_warning "This is expected - manual merges still needed"
fi

# ============================================================================
# SUMMARY
# ============================================================================

print_section "MERGE SUMMARY"

echo -e "\n${GREEN}✓ Completed:${NC}"
echo "  ✓ 41 files copied (Phase 12 features)"
echo "  ✓ Memory types renamed to avoid conflict"
echo "  ✓ Backup created at $BACKUP"
echo "  ✓ Type check attempted"

echo -e "\n${YELLOW}⚠ Manual Steps Required:${NC}"
echo "  1. Merge embeddings/types.ts with embeddings/types-phase12.ts"
echo "  2. Merge chunking plugins in $MERGE_DIR/plugins/"
echo "     - base-chunker.ts"
echo "     - event-based-chunker.ts"
echo "     - preference-signal-chunker.ts"
echo "     - step-based-chunker.ts"
echo "  3. Update memory/index.ts to export from experience-types.ts"
echo "  4. Update embeddings/index.ts after type merge"
echo "  5. Update chunking/index.ts to include new utilities"
echo "  6. Run full test suite: npm run test"
echo "  7. Build project: npm run build"

echo -e "\n${GREEN}📁 Files Created:${NC}"
echo "  - $ROOT/memory/experience-types.ts"
echo "  - $ROOT/embeddings/types-phase12.ts"
echo "  - $MERGE_DIR/plugins/*"

echo -e "\n${GREEN}📦 Backup Location:${NC}"
echo "  - $BACKUP/root-backup"

echo -e "\n${YELLOW}Next Steps:${NC}"
echo "  1. Review changes: git status"
echo "  2. Complete manual merges (see list above)"
echo "  3. Test: npm run test"
echo "  4. Build: npm run build"
echo "  5. Commit: git add . && git commit -m 'feat: Merge Phase 12 learning features'"

echo -e "\n${GREEN}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Automated Merge Complete!                 ║${NC}"
echo -e "${GREEN}║     Manual Steps Required - See Summary Above         ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════╝${NC}"

# ============================================================================
# CREATE MERGE CHECKLIST
# ============================================================================

cat > /home/aepod/dev/weave-nn/docs/migration-analysis/merge-checklist.md << 'CHECKLIST_EOF'
# Merge Checklist

## Automated Steps (✅ Complete)

- [x] Backup root implementation
- [x] Copy 41 Phase 12 files
- [x] Rename memory types to avoid conflict
- [x] Create plugin comparison files
- [x] Run initial type check

## Manual Steps (TODO)

### Type System Merges

- [ ] Merge `embeddings/types.ts`:
  - [ ] Combine root cache/hybrid types with nested model types
  - [ ] Add `IEmbeddingModel` and `IVectorStorage` interfaces
  - [ ] Add `BatchEmbeddingRequest` and `BatchEmbeddingResult`
  - [ ] Test imports across codebase

- [ ] Update `memory/index.ts`:
  ```typescript
  export * from './types.js';              // Vault sync
  export * from './experience-types.js';   // Learning
  export * from './claude-flow-client.js';
  export * from './vault-sync.js';
  export * from './experience-storage.js';
  export * from './experience-indexer.js';
  ```

### Plugin Merges

- [ ] Merge `chunking/plugins/base-chunker.ts`:
  - [ ] Compare root vs nested implementations
  - [ ] Add nested helper methods to root
  - [ ] Preserve root validation logic
  - [ ] Test with all chunking strategies

- [ ] Merge `chunking/plugins/event-based-chunker.ts`:
  - [ ] Add nested event detection features
  - [ ] Merge boundary detection logic
  - [ ] Test with episodic memory

- [ ] Merge `chunking/plugins/preference-signal-chunker.ts`:
  - [ ] Add nested signal detection
  - [ ] Merge decision extraction
  - [ ] Test with preference memory

- [ ] Merge `chunking/plugins/step-based-chunker.ts`:
  - [ ] Add nested step detection
  - [ ] Merge prerequisite handling
  - [ ] Test with procedural memory

### Index File Updates

- [ ] Update `chunking/index.ts`:
  ```typescript
  // Add new utilities
  export {
    detectHeadingBoundaries,
    detectParagraphBoundaries,
    detectCodeBlockBoundaries,
    detectListBoundaries,
    detectAllBoundaries,
  } from './utils/boundary-detector.js';

  export {
    extractContextBefore,
    extractContextAfter,
    extractContextAround,
    generateSummary,
  } from './utils/context-extractor.js';

  export {
    jaccardSimilarity,
    cosineSimilarity,
    detectSemanticBoundary,
  } from './utils/similarity.js';
  ```

- [ ] Update `embeddings/index.ts`:
  ```typescript
  // Add Phase 12 exports
  export { ModelManager } from './models/model-manager.js';
  export { VectorStorage } from './storage/vector-storage.js';
  export { BatchProcessor } from './batch-processor.js';
  ```

- [ ] Update `workflows/index.ts`:
  ```typescript
  // Add learning loop exports
  export * from './learning-loop/index.js';
  export * from './experience-integration.js';
  export * from './learning-loop-workflows.js';
  export * from './register-workflows.js';
  export * from './vector-db-workflows.js';
  ```

### Testing

- [ ] Unit tests:
  - [ ] `npm run test -- chunking`
  - [ ] `npm run test -- embeddings`
  - [ ] `npm run test -- memory`
  - [ ] `npm run test -- workflows/learning-loop`
  - [ ] `npm run test -- reasoning`
  - [ ] `npm run test -- reflection`

- [ ] Integration tests:
  - [ ] Test learning loop workflow
  - [ ] Test experience storage/retrieval
  - [ ] Test reasoning strategies
  - [ ] Test reflection engine

- [ ] Full suite:
  - [ ] `npm run test`
  - [ ] `npm run build`
  - [ ] `npm run typecheck`

### Documentation

- [ ] Update README with Phase 12 features
- [ ] Document learning loop workflow
- [ ] Document reasoning strategies
- [ ] Document experience memory system
- [ ] Update API documentation

### Cleanup

- [ ] Remove nested implementation: `rm -rf /home/aepod/dev/weave-nn/weave-nn/weaver`
- [ ] Remove backup after verification: `rm -rf /home/aepod/dev/weave-nn/.merge-backup`
- [ ] Remove comparison files: `rm -rf /home/aepod/dev/weave-nn/weaver/merge-comparison`
- [ ] Update `.gitignore` if needed

### Git Commit

- [ ] Stage all changes: `git add .`
- [ ] Review changes: `git status`
- [ ] Commit: `git commit -m "feat(phase-12): Merge learning loop features into root implementation"`
- [ ] Push: `git push`

---

**Progress**: 5/50 steps complete (10%)
**Estimated Time Remaining**: ~6-8 hours
**Next Priority**: Type system merges
CHECKLIST_EOF

print_success "Created merge checklist at docs/migration-analysis/merge-checklist.md"

echo -e "\n${GREEN}All done! Review the checklist and proceed with manual steps.${NC}"
